### ISSUE TITLE
Maneuver drift

### ISSUE THREAD

**Issue by schnoog** [linuxgurugamer/BetterTimeWarpContinued#11]
Problem description
copied from
http://forum.kerbalspaceprogram.com/index.php?/topic/160894-close-approach-and-maneuver-drift/

All the problems occurred with engines / RCS disbled.

During warp the problems stopped, when warp is leaved, they continue to nag me. 

Maneuver-drifting:
When I setup a maneuver, for example to do a Hohmann transfer to Mun, without touching the maneuver-node, the delta-v for the maneuver begins to increase, the maneuver indicator begins to drift away. After 1 minute over 2000m/s are displayed.

Closest approach drifting
I`ve setup an intercept with Duna from Kerbol orbit (just leaved Kerbins SOI). After a few seconds, the intercept switched to closest approach, which increased very fast so several million meter.

**Comment by linuxgurugamer** [comment]
Closed in favor of #19 Please see it for info on how to work around this
