### ISSUE TITLE
Using Lossless Physics with Accuracy other than 1 does not return to 1x

### ISSUE THREAD

**Issue by Atario** [linuxgurugamer/BetterTimeWarpContinued#13]
Steps:

1. Enable Lossless Physics and set Accuracy to anything but 1
1. Use any physics warp higher than 1x
1. Return to 1x speed
1. Observe clock:  it runs about double normal speed
1. Set Accuracy to 1
1. Observe clock:  it runs at normal speed again

**Comment by linuxgurugamer** [comment]
See my response to issue #19 

Closing this since it's a duplicate (predates, but I responded to 19 first)
