### ISSUE TITLE
Incompatibility with Stock Visual Terrain mod

### ISSUE THREAD

**Issue by ContraMuffin** [linuxgurugamer/BetterTimeWarpContinued#15]
Not sure where to post a bug/issue, but I discovered one.
I did a bunch of experimentation, and it seems like Better Time Warp and Stock Visual Terrain (with its dependencies, of course) together will, without fail, either crash or softlock the game. When one is installed without the other, the game runs without any errors. After a crash, Kopernicus will throw this error message:

> Kopernicus was not able to load the custom planetary system due to an exception in the loading process. Loading your savegame is NOT recommended, because the missing planets could corrupt it and delete your progress.
Please contact the planet pack author or the Kopernicus team about the issue and send them a valid bugreport, including your KSP.log, your ModuleManager.ConfigCache file and the folder Logs/Kopernicus/ from your KSP root directory

The forums post of Better Time Warp doesn't seem to have this incompatibility listed, so I assume it wasn't known.
I have attached my logs in case they're needed.
[Logs.zip](https://github.com/linuxgurugamer/BetterTimeWarpContinued/files/1575232/Logs.zip)

**Comment by Sigma88** [comment]
If I have time I'll take a look as well

Did you also try kopernicus + bettertimewarp to see if the problem is SVT or kopernicus?

**Comment by ContraMuffin** [comment]
Yes, I tested with SVE + EVE + Kopernicus + Better Time Warp, and that works. Seems to ONLY crash with SVT + Better Time Warp installed.

**Comment by linuxgurugamer** [comment]
Did you test this with Timecontrol (another mod which changes the time warping)?

**Comment by ContraMuffin** [comment]
linuxgurugamer, I went ahead and tested with SVT + Timecontrol + all my other mods. This combination works, and the game doesn't crash (though the loading screens are understandably slow). I haven't tested timewarping with Timecontrol, but since all the crashes happen during loading screens, I didn't feel a need to test out the time warp.

**Comment by ContraMuffin** [comment]
linuxgurugamer, StollD has discovered the root of the issue. It appears that there lacks enough memory when SVT and Better Time Warp are both installed - this is easily resolved by running 64-bit KSP.
