### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by FurkanS1821** [linuxgurugamer/BetterTimeWarpContinued#18]
I can't see this in the tooltip or near the warp HUD, it is not even in the loaded assemblies in Alt+F12 menu. Using it in KSP 1.4.4 with MechJeb, KerbalEngineer, TransferWindowPlanner and PreciseManeuver. Is this normal?

**Comment by linuxgurugamer** [comment]
Nope.

Sounds like you don't have the dependencies installed:

Click Through Blocker
ToolbarController

If that doesn't work, then a Log file, please

**Comment by FurkanS1821** [comment]
ty, it worked.
