### ISSUE TITLE
Incompatibility with TAC life support 

### ISSUE THREAD

**Issue by Evernow** [linuxgurugamer/BetterTimeWarpContinued#21]
Hello!

Whenever I try to time warp above what the game allows, my kerbals die, even the ones on other ships. They die mostly because of no electricity I believe, I can avoid this issue by freezing them but this isn't really a permanent fix as I often do very long trips with frequent stops, and I can't freeze them every single time... If any logs are required feel free to ask!

**Comment by linuxgurugamer** [comment]
Please try it with Time Control (another timewarp mod).  If it happens with that, then contact the Tac author

**Comment by Evernow** [comment]
> Please try it with Time Control (another timewarp mod). If it happens with that, then contact the Tac author

(By the way, love all your mods!)

Sorry for wasting your time, I did try that mod and the same exact thing happened. I will contact the TAC author now! Thank you for all your hard work!

**Comment by linuxgurugamer** [comment]
Not a problem.  Good luck
