### ISSUE TITLE
Log being spammed with "Launcher here(in write)"

### ISSUE THREAD

**Issue by tivec** [linuxgurugamer/BetterTimeWarpContinued#22]
https://github.com/linuxgurugamer/BetterTimeWarpContinued/blob/f5dfdb0aa9d46aefb012ce1daa613e82e7c0df7b/BetterTimeWarp/BetterTimeWarp.cs#L870

While the actual log message "Launcher here(in write): False" seems to be coming from the KSP source, this is triggered in FixedUpdate as linked above.

Stack trace from KSPDev LogConsole:
![image](https://user-images.githubusercontent.com/717574/55152109-f79c6980-514f-11e9-82c8-9723f50915aa.png)

**Comment by linuxgurugamer** [comment]
Sorry, I don't understand.  Is this affecting the game?  or are you just reporting a message shown by an alternative logging mechanism?

This is a KSP problem, if even that.  Looks like they left a debug line there which gets triggered under certain circumstances, but it's not a bug in BTW

I've reported it to Squad

**Comment by tivec** [comment]
Yes, it is definitely affecting the game. Check the number of repeats (7576), which is in less than a minute. This is then deposited into KSP.log like this, causing frequent stutter:

[LOG 11:30:36.927] Launcher here(in write): False
[LOG 11:30:36.944] Launcher here(in write): False
[LOG 11:30:36.961] Launcher here(in write): False
[LOG 11:30:36.978] Launcher here(in write): False
[LOG 11:30:36.994] Launcher here(in write): False
[LOG 11:30:37.027] Launcher here(in write): False
[LOG 11:30:37.044] Launcher here(in write): False
[LOG 11:30:37.061] Launcher here(in write): False
[LOG 11:30:37.077] Launcher here(in write): False
[LOG 11:30:37.094] Launcher here(in write): False
[LOG 11:30:37.128] Launcher here(in write): False
[LOG 11:30:37.146] Launcher here(in write): False
[LOG 11:30:37.161] Launcher here(in write): False
[LOG 11:30:37.178] Launcher here(in write): False
[LOG 11:30:37.195] Launcher here(in write): False
[LOG 11:30:37.228] Launcher here(in write): False
[LOG 11:30:37.245] Launcher here(in write): False
[LOG 11:30:37.262] Launcher here(in write): False
[LOG 11:30:37.278] Launcher here(in write): False
[LOG 11:30:37.295] Launcher here(in write): False
[LOG 11:30:37.327] Launcher here(in write): False
[LOG 11:30:37.344] Launcher here(in write): False
[LOG 11:30:37.361] Launcher here(in write): False
[LOG 11:30:37.378] Launcher here(in write): False
[LOG 11:30:37.395] Launcher here(in write): False
[LOG 11:30:37.428] Launcher here(in write): False
[LOG 11:30:37.444] Launcher here(in write): False
[LOG 11:30:37.462] Launcher here(in write): False
[LOG 11:30:37.478] Launcher here(in write): False
[LOG 11:30:37.495] Launcher here(in write): False
[LOG 11:30:37.528] Launcher here(in write): False
[LOG 11:30:37.544] Launcher here(in write): False
[LOG 11:30:37.562] Launcher here(in write): False
[LOG 11:30:37.579] Launcher here(in write): False
[LOG 11:30:37.595] Launcher here(in write): False
[LOG 11:30:37.628] Launcher here(in write): False
[LOG 11:30:37.645] Launcher here(in write): False
[LOG 11:30:37.662] Launcher here(in write): False
[LOG 11:30:37.679] Launcher here(in write): False
[LOG 11:30:37.695] Launcher here(in write): False
[LOG 11:30:37.728] Launcher here(in write): False
[LOG 11:30:37.744] Launcher here(in write): False
[LOG 11:30:37.761] Launcher here(in write): False
[LOG 11:30:37.778] Launcher here(in write): False
[LOG 11:30:37.795] Launcher here(in write): False

Repeated ad nauseum. I disabled BetterTimeWarpContinued and have not yet gotten a single log message.

I understand that it is a Squad bug, but I'm just letting you know that this mod is what triggers it from outside the KSP source.

**Comment by linuxgurugamer** [comment]
Ok, I'll see if I can reduce the number of calls

**Comment by linuxgurugamer** [comment]
and fixed
