### ISSUE TITLE
Remove version file missing

### ISSUE THREAD

**Issue by HebaruSan** [linuxgurugamer/BetterTimeWarpContinued#25]
Most of the spacetux.net remote version files are working now (thanks!), but this one is still having trouble:

- http://ksp.spacetux.net/avc/BetterTimeWarp

Maybe it went missing?

**Comment by linuxgurugamer** [comment]
This one is an oddball, there were two, one for 1.7.3 and one for 1.8.0.  I made the 1.8.0 the current one since1.7.3 is not being updated anymore
