### ISSUE TITLE
Battery Scaling

### ISSUE THREAD

**Issue by blahblahbloopster** [linuxgurugamer/BetterTimeWarpContinued#28]
I'm playing with some other mods, and my spacecraft needs a constant, large supply of power (about 240 units per second) or it will explode.  On low warp settings it works alright as generation and consumption are both scaled, but at very high warps the craft explodes.  I've spammed RTGs to isolate the issue and it has an excess of power normally.  I think it has to do with storage; normally in a tick, 4 units are used then 4 units are produced, but at 10 million times acceleration 40 million units are used, overdrawing the batteries (see [here](https://www.reddit.com/r/KerbalSpaceProgram/comments/79hev7/running_out_of_power_at_highest_timewarp_speed/)).  Because I can't put 40 million units of storage on my ship, I propose that the mod scale battery capacity in addition to consumption and generation to mitigate this issue.

**Comment by linuxgurugamer** [comment]
Have you tried Time Control?  It's another time warp mod, and it does somethings that BTW doesn't.
Would be better to post things like this on the KSP Forums, where other people can help and make suggestions

I'm not planning on doing anything with it at this time, but I'll leave it open for now

**Comment by blahblahbloopster** [comment]
I'll take a look at that, thanks!  I temporarily 'fixed' it already by adding a bunch of zeroes to a battery pack's capacity in the part config files.

**Comment by linuxgurugamer** [comment]
The problem is that this mod doesn't actually do the time warping, it just changes the scaling.  I'll be taking a look, but not hopeful about it

**Comment by linuxgurugamer** [comment]
I looked into this, and it's actually quite complicated.  There is a lot of interactions that you wouldn't normally think about.  For example, what happens to vessels that are not in physics range?  what happens if you change vessels while timewarping?  etc.
sorry to say, too far outside the bounds of this mod
