### ISSUE TITLE
<1x timewarp abnormal behaviour

### ISSUE THREAD

**Issue by Kerbinator-Fras** [linuxgurugamer/BetterTimeWarpContinued#29]
<1x timewarp will make orbit params change quickly for no reason. idk why, and this orbit change applies in timewarp where no force should exist.

**Comment by linuxgurugamer** [comment]
A report in a vacuum doesn't help.  I need to have a log file, and (at a minimum) a list of all mods that you have installed

**Comment by linuxgurugamer** [comment]
Also, posting in the forum can often get faster response

**Comment by Kerbinator-Fras** [comment]
![image](https://user-images.githubusercontent.com/55748582/142425895-c12c69f3-e509-4337-b9c3-4cc73f846a85.png)
[KSP.log.zip](https://github.com/linuxgurugamer/BetterTimeWarpContinued/files/7563253/KSP.log.zip)
mods
![image](https://user-images.githubusercontent.com/55748582/142427293-19d1e5eb-46aa-401f-aa6d-6652b0e9ac4b.png)

**Comment by Kerbinator-Fras** [comment]
the log is in zip file

**Comment by linuxgurugamer** [comment]
If I understand the pic, you are at a timewarp of 0.01?  You are just asking for floating point errors.

This is inherent in KSP, and a timewarp of 0.01 is just abusing the system.

Sorry, it's not a bug.  I suggest that you possibly post on the forum for some help
