### ISSUE TITLE
CKAN lists "zero MiniAVC" as dependency

### ISSUE THREAD

**Issue by OddSobriquet** [linuxgurugamer/BetterTimeWarpContinued#31]
So I'm just coming over after having embarrassed myself at the KIS repo and I'm ready to do it again ;)
I'm not that savvy when it comes to mods but i try my best to make sense of everything.

So, installing Better Time Warp [further BTW] (and 3 other unrelated mods: click through blocker, minimum ambient lighting, toolbar controller) through CKAN, BTW lists "zero miniAVC" as a dependency. attempting to uninstall "zero miniAVC" through ckan thus will also uninstall BTW.
unfortunately, zero miniAVC breaks several other mods (KIS for instance) by making module manager really unhappy (can't blame it though, as it does work as designed). I now have uninstalled zero miniAVC, by removing the mod from the GameData folder manually and so far I couldn't find this breaking BTW (or any of the other mentioned mods).

I have BTW 2.3.13 installed and cached. I tried removing it from CKAN cache and downloading it again, just in case that made a difference, it didn't.

Is the dependency still up to date?

**Comment by linuxgurugamer** [comment]
This is not a support forum, please direct all requests for support to the forum.

Regarding ZeroMiniAVC causing problems, you are the first person ever to report this.  

I suggest that you post a message in the forum where ZeroMiniAVC is supported:

https://forum.kerbalspaceprogram.com/index.php?/topic/174445-19x-malahs-quick-mods/

You have the latest versions installed, assuming you are using CKAN

**Comment by linuxgurugamer** [comment]
When you post on the forums, please include a link to the Player.log, won't be able to help without that

**Comment by OddSobriquet** [comment]
not a member of the forum and tbh I don't feel like signing up for just this single post.

I'm not the first person ever to report this, as it was [reported before](https://forum.kerbalspaceprogram.com/index.php?/topic/174445-112x-malahs-quick-mods-important-update-for-zerominiavc/page/13/#comment-4044379) and you supposedly fixed it in 1.1.2.3 ZMAVC.
Either something got changed back from 1.1.2.3 to 1.1.2.4 or KSP 1.12.4 had a change.

I can open a ticket on the quickMods repo with detailed explanation and logs, if you want me to.

**Comment by linuxgurugamer** [comment]
I still need the player.log, without that, no help can possibly be provided
Also, that error you linked to was in ModuleManager, which is not unexpected.  But I assume you have restarted it multiple times

**Comment by OddSobriquet** [comment]
[KSP.log](https://github.com/linuxgurugamer/BetterTimeWarpContinued/files/9990774/KSP.log)
[Player.log](https://github.com/linuxgurugamer/BetterTimeWarpContinued/files/9990786/Player.log)

video for behaviour clarification
https://user-images.githubusercontent.com/72888738/201357207-87ad6837-e70d-4e9f-b13d-db6192ec1ae8.mp4

I'm sorry I wasn't myself yesterday.
As I said, I try my best to understand it to the best of my ability.

Once I remove the zerominiAVC folder from the gamedata folder it works just fine with the other mods working fine as well.
Also, I noticed that this is technically not even the correct repository as BTW isn't directly dependent on ZMAVC but on CTB and Toolbar controller which in turn have the dependency.

**Comment by linuxgurugamer** [comment]
This actually looks like a ModuleManager error, while it is having an error with the MiniAVC-V2.dll, the error is in ModuleManager:

I'm going to guess that it's realted to the spaces in the file name.  Try copying the entire directory into a new folder on your desktop and see if it happens there.
Regardless, this is not an error in ZeroMiniAVC or MiniAVC-v2, but it's related to those being installed.  

`Uploading Crash Report
[ModuleManager] The patching thread threw an exception: System.IO.FileNotFoundException: C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\KIS\Plugins\MiniAVC-V2.dll
  at System.Diagnostics.FileVersionInfo.GetVersionInfo (System.String fileName) [0x0000d] in <ef151b6abb5d474cb2c1cb8906a8b5a4>:0 
  at ModuleManager.ModListGenerator.GenerateModList (System.Collections.Generic.IEnumerable`1[T] modsAddedByAssemblies, ModuleManager.Progress.IPatchProgress progress, ModuleManager.Logging.IBasicLogger logger) [0x000a2] in <ac37db06097f4706b70066f555f86981>:0 
  at ModuleManager.MMPatchLoader.Run () [0x000f3] in <ac37db06097f4706b70066f555f86981>:0 
  at ModuleManager.MMPatchRunner+<>c__DisplayClass10_0.<Run>b__1 () [0x00001] in <ac37db06097f4706b70066f555f86981>:0 
  at ModuleManager.Threading.BackgroundTask+<>c__DisplayClass0_0.<Start>g__RunAction|0 () [0x00002] in <ac37db06097f4706b70066f555f86981>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
`

**Comment by linuxgurugamer** [comment]
I've posted this in the ModuleManager forum:  https://forum.kerbalspaceprogram.com/index.php?/topic/50533-18x-112x-module-manager-422-june-18th-2022-the-heatwave-edition/&do=findComment&comment=4197856

**Comment by OddSobriquet** [comment]
I read and checked for some reason the behaviour changed from yesterday's....
Yesterday, it would still crash even after the KIS miniAVC-v2.dll was pruned. Today, it doesn't. I'm at a total loss. I did try multiple times yesterday to remove them both as well as just restart after the initial module manager crash and the symptoms were different...

I am really sorry to have caused so much confusion. I massively appreciate your effort and dedication.
Again sorry for being a little b*tch yesterday.

**Comment by linuxgurugamer** [comment]
Hi,
I found the problem:
Ok.  This is a bug in ModuleManager, I've found and fixed it locally, will be pushing a PR with the change

I believe in pre 1.12.4, MM was seeing the same error, but not crashing on it.  Probably due to a change in the order things are loading in.

The reason it worked for you was a timing issue.  MM was seeing a list of all the DLLs, but before it is able to open the file, it get's pruned by ZeroMiniAVC.

Don't remove the ZeroMiniAVC folder, that's needed in case you reload an mods with the old MiniAVC.dll, which crashes the game.  Just keep restarting until it clears

**Comment by OddSobriquet** [comment]
you're an absolute hero! Thank you so much!

**Comment by linuxgurugamer** [comment]
There is a beta for ZZeroMiniAVC which also fixes this issue

Read about it here:
https://forum.kerbalspaceprogram.com/index.php?/topic/210628-zerominiavc-development-thread-beta-testers-needed/&do=findComment&comment=4199266

and download the beta from here:
https://github.com/linuxgurugamer/ZeroMiniAVC/releases
