### ISSUE TITLE
Electric power calculation goes wrong when using high time warp

### ISSUE THREAD

**Issue by gangzhengzhiwei** [linuxgurugamer/BetterTimeWarpContinued#32]
The electric power calculation seems goes wrong when using time warp over 100,000x.
I put a satellite in the solar orbit,but the power was rapidly reduced often,sometimes even the cell was empty.Then the power is rising rapidly untill the cell is full.This has already led to some disastrous consequences,and only happened when I using the time warp over 100,000x.But never happened in Standard Warp mode.(My english is very poor)

**Comment by linuxgurugamer** [comment]
Nothing to do with this mod, it's KSP.
