### ISSUE TITLE
Time Warps being reverted and changed after game restart

### ISSUE THREAD

**Issue by Clayell** [linuxgurugamer/BetterTimeWarpContinued#33]
I've been having an issue for the past few days now where my last chosen time warp (aka before I exit the game) will get reset to:

10

100

1,000

10,000

100,000

1,000,000

6,000,000

 

And then my standing warp which was previously those sequence of numbers (and which is also uneditable without going into the cfg file) will turn into:

5

10

50

100

1,000

10,000

100,000

 

This bug is really starting to be annoying to me, especially because I have tried some fixes in the cfg and I have also uninstalled and reinstalled the mod, but it is still broken. I have to reset my time warp values every time I play a new ksp session, which is annoying. I also haven't encountered this bug previously, only on this RSS/RO install. Can someone (preferably linx?) help? My logs are below:

Player.log:

https://drive.google.com/file/d/1iT_ircIlwl5S69vFUtJfXwYtAgSU50RN/view?usp=share_link

 

KSP.log:

https://drive.google.com/file/d/15rVxrGOEBac0jL09lCFmAtO8MrOvmc74/view?usp=share_link

 

(this is a repost from the ksp forums)

**Comment by Clayell** [comment]
This is still an issue btw

**Comment by linuxgurugamer** [comment]
The mod saves it's data in the save file, so uninstalling and reinstalling won't help.  You would have to go through the save file to fully remove all references to BetterTimeWap.

That being said, it seems that RO has something called CameraTools which is doing something with the mod.

Also, I see that you have TimeControl installed, you really should only have one

**Comment by Clayell** [comment]
I’ve downloaded cameratools through ckan myself, unless ro has something by that name which is unrelated.

Where do you see time control? I’ve never heard of that.

**Comment by linuxgurugamer** [comment]
In the log file, maybe it gets included with  RO

**Comment by Clayell** [comment]
The only thing I can think of that involved RO and timewarp was persistent rotation, which I don’t think is related. How should I fix this bug?

**Comment by Clayell** [comment]
Any updates?

**Comment by linuxgurugamer** [comment]
Not really, sorry.  I can't find anything wrong, it works for all situations I've tried (I don't do RO).

**Comment by Clayell** [comment]
Alright, I’ll ask around in the RO server and see if anyone else has the problem.

**Comment by Clayell** [comment]
I'm now confident that RSS or something along those lines actually sets the default time warp to what I said above automatically, which would explain why it was always getting overridden. You can still select the different time warp modes with this mod, the default setting is just different than stock.

**Comment by Clayell** [comment]
> I'm now confident that RSS or something along those lines actually sets the default time warp to what I said above automatically, which would explain why it was always getting overridden. 

Yes, those values are set at:
[RealSolarSystem/GameData/RealSolarSystem/RealSolarSystem.cfg](https://github.com/KSP-RO/RealSolarSystem/blob/2d9b07083409fd5cc8f3769924023be8333899cd/GameData/RealSolarSystem/RealSolarSystem.cfg#L21-L31)

Which can easily be modified or removed by the user.

Relevant RSS Issue: https://github.com/KSP-RO/RealSolarSystem/issues/305

**Comment by linuxgurugamer** [comment]
Thank you
