### ISSUE TITLE
Dropdown icon covers CommNet icons when signal goes through a relay.

### ISSUE THREAD

**Issue by DrRaphello** [linuxgurugamer/BetterTimeWarpContinued#7]
The dropdown button covers CommNet icons when a relay is between ship and Kerbin.
V 2.3.4 from CKAN

![20170207-202028-sun-orbiting](https://cloud.githubusercontent.com/assets/25507737/22707608/9be9ad4c-ed73-11e6-9b82-24844c964409.png)

**Comment by DrRaphello** [comment]
One more example of incorrect placing
![20170209-004126-moho-landed_cr](https://cloud.githubusercontent.com/assets/25507737/22763005/91a359e2-ee62-11e6-98a3-4a986c5637de.jpg)

**Comment by linuxgurugamer** [comment]
Fixed in release
