### ISSUE TITLE
Lossless physics warp causes maneuver nodes to drift off target

### ISSUE THREAD

**Issue by Thorbane** [linuxgurugamer/BetterTimeWarpContinued#9]
Also causes unloaded craft to move much faster than they should.

I suspect both maneuver nodes and unloaded craft aren't sharing the change in delta time.

**Comment by linuxgurugamer** [comment]
What time-warp rate are you using?
From what I saw, if the time-warp is >100, it doesn't matter if lossless is set or not

**Comment by Thorbane** [comment]
I was using 3x, 6x, and 8x lossless.  I saw jettisoned and unloaded parts that were going slower than my ship suddenly rush ahead at a speed proportional to the physics warp setting, which makes me think they're still behaving as if their physics is still calculated using a larger timestep.

**Comment by linuxgurugamer** [comment]
If you could do a video, that would help.
I don't have time right now, but hope to look at this in a day or so

**Comment by linuxgurugamer** [comment]
I also need to know the following:

1. Was Physics Warp enabled (in the list of the speeds)?
2. What was the Lossless Physics Accuracy?

**Comment by linuxgurugamer** [comment]
Fixed
